# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TheMovieDB' do
  use_frameworks!

  pod 'Alamofire', '~> 4.5.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Bond', '~> 6.0-beta'
  pod 'RAMAnimatedTabBarController'
  pod 'youtube-ios-player-helper'
  pod 'SDWebImage'
  pod 'AXPhotoViewer'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GhostTypewriter'
  pod 'ProcessLoadingView'
  pod 'Charts'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'XCDYouTubeKit'
  pod 'FCAlertView'
  pod 'NVActivityIndicatorView'
  
  # Pods for TheMovieDB

  target 'TheMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
